# Generated by Django 3.2.4 on 2021-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='temp', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='liked_songs',
            field=models.JSONField(default='temp'),
            preserve_default=False,
        ),
    ]
