# Generated by Django 3.2.4 on 2021-06-13 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0003_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
